package com.SkrinVex.syncwave.app.cookies

import android.webkit.CookieManager
import com.SkrinVex.syncwave.app.domain.model.Resource
import com.SkrinVex.syncwave.app.domain.repository.SettingsRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class GoogleAuthManager(
    private val settingsRepository: SettingsRepository
) {
    companion object {
        val CORE_AUTH_COOKIES = setOf(
            "LOGIN_INFO",
            "SAPISID",
            "__Secure-1PSID",
            "__Secure-3PSID",
            "SID",
            "SSID",
            "HSID",
            "APISID",
            "__Secure-1PAPISID",
            "__Secure-3PAPISID"
        )
    }

    /**
     * Inspects cookies in android.webkit.CookieManager for YouTube / Google domains
     * and returns true if critical YouTube Music authentication tokens are found.
     */
    fun hasAuthCookies(): Boolean {
        val cookieManager = CookieManager.getInstance()
        val musicCookies = cookieManager.getCookie("https://music.youtube.com") ?: ""
        val ytCookies = cookieManager.getCookie("https://youtube.com") ?: ""
        val googleCookies = cookieManager.getCookie("https://accounts.google.com") ?: ""

        val combined = "$musicCookies; $ytCookies; $googleCookies"
        return CORE_AUTH_COOKIES.any { combined.contains("$it=") }
    }

    /**
     * Extracts all cookies from CookieManager across YouTube and Google domains,
     * formats them into standard Netscape HTTP Cookie file format, and uploads to SyncWave backend.
     */
    suspend fun syncCookiesToServer(): Resource<Boolean> = withContext(Dispatchers.IO) {
        val cookieManager = CookieManager.getInstance()
        val targetUrls = listOf(
            "https://music.youtube.com",
            "https://www.youtube.com",
            "https://youtube.com",
            "https://accounts.google.com",
            "https://google.com",
            "https://myaccount.google.com"
        )

        val cookieMap = mutableMapOf<String, String>()

        for (url in targetUrls) {
            val cookieStr = cookieManager.getCookie(url) ?: continue
            val pairs = cookieStr.split(";")
            for (pair in pairs) {
                val trimmed = pair.trim()
                if (trimmed.isBlank() || !trimmed.contains("=")) continue
                val eqIdx = trimmed.indexOf("=")
                val name = trimmed.substring(0, eqIdx).trim()
                val value = trimmed.substring(eqIdx + 1).trim()
                if (name.isNotEmpty()) {
                    cookieMap[name] = value
                }
            }
        }

        if (cookieMap.isEmpty() || !CORE_AUTH_COOKIES.any { cookieMap.containsKey(it) }) {
            return@withContext Resource.Error("Авторизационные куки YouTube Music не обнаружены. Пожалуйста, выполните вход в аккаунт.")
        }

        val netscapeBuilder = StringBuilder()
        netscapeBuilder.append("# Netscape HTTP Cookie File\n")
        netscapeBuilder.append("# http://curl.haxx.se/rfc/cookie_spec.html\n")
        netscapeBuilder.append("# Generated by SyncWave Android Client\n\n")

        val expiry = System.currentTimeMillis() / 1000L + (365L * 24L * 3600L) // 1 year expiry fallback

        for ((name, value) in cookieMap) {
            // Write for .youtube.com
            netscapeBuilder.append(".youtube.com\tTRUE\t/\tTRUE\t$expiry\t$name\t$value\n")
            // Write for .google.com
            netscapeBuilder.append(".google.com\tTRUE\t/\tTRUE\t$expiry\t$name\t$value\n")
        }

        val netscapeContent = netscapeBuilder.toString()
        settingsRepository.uploadCookiesText(netscapeContent)
    }

    /**
     * Clears all session and persistent cookies in the WebView CookieManager.
     */
    fun clearWebViewCookies(onComplete: (() -> Unit)? = null) {
        val cookieManager = CookieManager.getInstance()
        cookieManager.removeAllCookies {
            cookieManager.flush()
            onComplete?.invoke()
        }
    }
}

